### ISSUE TITLE
Add clang 3.5 support

### ISSUE THREAD

**Issue by robert-zaremba** [zdevito/terra#77]
Now, the default LLVM version is 3.5. Terra won't build on LLVM 3.5:

```
/usr/bin/clang++ -Wall -g -I build/LuaJIT-2.0.3/src -I /usr/include -I /usr/include -I build -fPIC  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O0 -fno-rtti -fno-common -Woverloaded-virtual -Wcast-qual -fvisibility-inlines-hidden -DLLVM_VERSION=35 -DTERRA_CLANG_RESOURCE_DIRECTORY="\"/usr/lib/clang/3.5.0\"" -DTERRA_LLVM_HEADERS_HAVE_NDEBUG -std=c++11 -Wno-c++11-narrowing src/tcwrapper.cpp -c -o build/tcwrapper.o
src/tcwrapper.cpp:27:1: error: expected expression
using namespace clang;
^
src/tcwrapper.cpp:750:2: error: expected '}'
}
 ^
build/clangpaths.h:1:37: note: to match this '{'
static const char * clang_paths[] = {
                                    ^
src/tcwrapper.cpp:750:2: error: expected ';' after top level declarator
}
 ^
 ;
3 errors generated.
Makefile:248: recipe for target 'build/tcwrapper.o' failed
```

**Comment by zdevito** [comment]
Terra should work with 3.5, it is what I use now. It looks like something
has gone wrong earlier in your build. Can you run 'make clean', and build
again. The full log might let me see what is going on.

**Comment by robert-zaremba** [comment]
Works fine now. I don't know what went wrong before. Sorry for troubles.
