### ISSUE TITLE
Terra's dependency on llvm/PassManager.h make it incompatible with LLVM 3.7

### ISSUE THREAD

**Issue by yuhangwang** [zdevito/terra#125]
I have downloaded the binary for clang+llvm 3.7 and used to compile Terra. However, I got this error 

> 1 error generated.
>     In file included from src/tinline.cpp:7:
>     src/llvmheaders.h:20:10: fatal error: 'llvm/PassManager.h' file not found
>     #include "llvm/PassManager.h"

Here is the folder structure of include/llvm:

> ├── ADT
> ├── Analysis
> ├── AsmParser
> ├── Bitcode
> ├── CodeGen
> ├── Config
> ├── DebugInfo
> ├── ExecutionEngine
> ├── InitializePasses.h
> ├── IR
> ├── IRReader
> ├── LibDriver
> ├── LineEditor
> ├── LinkAllIR.h
> ├── LinkAllPasses.h
> ├── Linker
> ├── LTO
> ├── MC
> ├── Object
> ├── Option
> ├── PassAnalysisSupport.h
> ├── Passes
> ├── Pass.h
> ├── PassInfo.h
> ├── PassRegistry.h
> ├── PassSupport.h
> ├── ProfileData
> ├── Support
> ├── TableGen
> ├── Target
> └── Transforms

Notice there is no PassManager.h anymore.  Do you think Terra will be compatible with llvm 3.7 soon?

**Comment by zdevito** [comment]
I haven't had time to update the source to work with LLVM 3.7 yet. Not sure
when I will get to it. I recommend using the binary distributions if you
can, or using LLVM 3.5 or 3.6.

-- Zach

**Comment by yuhangwang** [comment]
I see. Thanks.

**Comment by HalosGhost** [comment]
@zdevito, do you have a plan or a timeline for adding support for LLVM 3.7? I've often been deeply tempted by terra, but as I'm an Arch user, I really only have the latest version of everything available. If there's a set of tasks needed to move forward with the port, I would be happy to help too.

**Comment by zdevito** [comment]
I am not sure when I will be able to get to do it. The port is actually
quite involved and normally takes me a couple whole days. It requires:

1. fixing all build problems including header movement and API changes,
which requires normally looking at diff's of LLVM files because the API
aren't otherwise documented.

2. Running the test suite and debugging any API changes that weren't
reflected in the types of the API. There are normally 1--2 of these issue
that crop up for every release.

3. Running a few performance tests and looking at the speed and quality of
code generated from the previous version, making sure no performance
regressions took place.

Instead, I recommend using the binary releases if possible since they don't
require you to even have llvm installed. If not, it is still possible to
download an older version of LLVM and use that for the build without
installing it (Just point LLVM_CONFIG in Terra's make file to that
version).  Most tools that internally use LLVM don't use the system's LLVM
anyway, since they change the API so aggressively.

**Comment by elliottslaughter** [comment]
Closing since we've moved past LLVM 3.7 a long time ago.
